### ISSUE TITLE
How to import the part of advanced demo in Ionic V4 ?

### ISSUE THREAD

**Issue by vise92** [KillerCodeMonkey/ngx-quill-ionic-v4#2]
How to import  integration of quill-emoji integration of quill-mention integration of quill-image-resize custom word count module custom toolbar with custom fonts and formats, toolbar position show the differences between sanitizing and not sanitizing your content if your content format is html usage of different content formats template-driven and reactive forms code + syntax highlighting formulas custom key-bindings, e.g. shift + b for bold dynamic styles and placeholder toggle readonly bubble toolbar activate formats after editor initialisation, e.g. rtl direction present quilljs content with the quill-view and quill-view-html component in the ionic v4 ?

**Comment by KillerCodeMonkey** [comment]
the same way it is done in the advanced demo.
ionic uses angular cli so you can just copy the interesting parts from the angular.json and the app.module.ts to your project.

**Comment by vise92** [comment]
I'll let you know if I have problems.

thanks a lot
