### ISSUE TITLE
How do i get the value of the quill container in console.log ?

### ISSUE THREAD

**Issue by ersaurabh101** [KillerCodeMonkey/ngx-quill-ionic-v4#4]
Hello,

Please guide me, how do i get the value of all the text and images[as quill converts it to base 64] in a variable ?

**Comment by KillerCodeMonkey** [comment]
Just Checkout The ngx-quill repo and documentation . You can usw angular
reactive or template driven Forms. Or Just listen to The onContentChanged
Output.

If you want the content as quilljs delta and Not AS html Just Set the
Format Input to "object" or "json".

ersaurabh101 <notifications@github.com> schrieb am Do., 5. März 2020, 07:04:
